pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Local SDK distribution. Generated by `./gradlew publish` in ../
        maven {
            name = "localSdk"
            url = uri("../dist/repo")
        }
    }
}

rootProject.name = "demo"

include(":app")

// Toggle between live source (composite build) and the published AAR/POM
// artifacts under ../dist/repo. Pass `-PuseLocalSdk` to consume the artifacts.
if (!providers.gradleProperty("useLocalSdk").isPresent) {
    includeBuild("..")
}
